### ISSUE TITLE
Where's the source to WebViewInterface.jar?

### ISSUE THREAD

**Issue by roblav96** [shripalsoni04/nativescript-webview-interface#10]
I'm curious how you've made this work. Calling `addJavascriptInterface` from nativescript does nothing.

**Comment by shripalsoni04** [comment]
You can check the android WebViewInterface source code at https://github.com/shripalsoni04/android-webview-interface and code of `JavascriptInterface` at https://github.com/shripalsoni04/android-webview-interface/blob/master/app/src/main/java/com/shripalsoni/natiescriptwebviewinterface/WebViewInterface.java

Hope this will help.

**Comment by roblav96** [comment]
@shripalsoni04 awesome! thanks mate!
