### ISSUE TITLE
Android: Refusing to load URL as it exceeds X characters.

### ISSUE THREAD

**Issue by danielgek** [shripalsoni04/nativescript-webview-interface#18]
When you try to send a long message this error appears:
`chromium: [WARNING:navigator_impl.cc(343)] Refusing to load URL as it exceeds 2097152 characters.`
This happens because of the targetSdkVersion in manifest is 19+ ( base on chromium ). So, you can use the evaluateJavascript() method instead of loadUrl. loadUrl only work fine without above error in version 18-. https://developer.android.com/guide/webapps/migrating.html. 

I will send PR shortly

**Comment by surdu** [comment]
This should have been fixed in #17

**Comment by shripalsoni04** [comment]
As mentioned by @surdu , this should be fixed now because PR #17 is already merged.
