### ISSUE TITLE
Not loading a Ionic3 webapp in webview

### ISSUE THREAD

**Issue by demym** [shripalsoni04/nativescript-webview-interface#20]
Hi, 

i tried to load the built www of an Ionic3 app, but for some reason it does not load (the console shows me an error, but do not specifies which one....).

The built www works perfectly in a browser.

No problem instead with a Jquery mobile based on.

Thanks in advance

**Comment by shripalsoni04** [comment]
I think this problem should be related to nativescript web-view widget and not to this plugin. Please raise an issue on nativescript repository with some sample repository.

Thanks.
