### ISSUE TITLE
Cannot read property 'emit' of undefined

### ISSUE THREAD

**Issue by pollyolly** [shripalsoni04/nativescript-webview-interface#48]
"Uncaught TypeError: Cannot read property 'emit' of undefined",

Inside the html file. 

I tried to include it this way **<script src="./lib/nativescript-webview-interface.js"></script>** based on the instruction.

I badly need this plugin for my project. Please help.

**Comment by pollyolly** [comment]
Fixed:

I added {from: "www/**"} in webpack config. It seems adding .html is not sufficient.

**Comment by Ot92** [comment]
Having the same problem, browser recognises window.nsWebViewInterface on desktop but through the webview, it's undefined. 

Where exactly do you add the line below in Nativescript webpack?

` {from: "www/**"}`

**Comment by ghost** [comment]
> Having the same problem, browser recognises window.nsWebViewInterface on desktop but through the webview, it's undefined.
> 
> Where exactly do you add the line below in Nativescript webpack?
> 
> ` {from: "www/**"}`

in webpack.config.js

**Comment by ghost** [comment]
but for me even adding this wont help,

I can run `this.oWebViewInterface.on( 'onStateChange', eventData => {} )`

and it works, but not `.emit` nor `.callJSFunction` wont work for me.

Android 10 | NS 7

I get this error: `TypeError: Cannot read property 'sdkVersion' of undefined`

to solve this problem I changed the plug-in ( file:  `index.android.js` ) a bit:


line 2 from `const platformModule = require("platform");` to `const platformModule = require("@nativescript/core");` 

and

line 79 from `if (platformModule.device.sdkVersion >= 19) {` to `if (platformModule.Device.sdkVersion >= 19) {`
