### ISSUE TITLE
Upgrade to Nativescript 7

### ISSUE THREAD

**Issue by crechberger** [shripalsoni04/nativescript-webview-interface#57]
Hey,

Nativescript recenlty introcuded some big changes (for example they changed the compiler option from "ES-5" to "ES2017"). It would be great if you could bring the whole project up to date. 

Here's the url with all the instructions: [https://nativescript.org/blog/nativescript-7-for-plugin-authors/](https://nativescript.org/blog/nativescript-7-for-plugin-authors/)

Thank you :)

**Comment by szhatef** [comment]
changed the plug-in ( file: index.android.js ) a bit:

line 2 from const platformModule = require("platform"); to const platformModule = require("@nativescript/core");

and

line 79 from if (platformModule.device.sdkVersion >= 19) { to if (platformModule.Device.sdkVersion >= 19) {

**Comment by shripalsoni04** [comment]
Fixed in version @1.4.4.

**Comment by crechberger** [comment]
Thanks :)
